### ISSUE TITLE
transfer ownership of 'hyperledger' namespace in DockerHub to LF

### ISSUE THREAD

**Issue by christo4ferris** [hyperledger/hyperledger#23]
transfer ownership of 'hyperledger' namespace in DockerHub to LF from ramesh(IBM)

**Comment by srderson** [comment]
This has been transferred to @rjones-lf

**Comment by christo4ferris** [comment]
I believe this to be closed... @rjones-lf @ghaskins @rameshthoomu can you please confirm?

**Comment by rjones-lf** [comment]
ownership is transferred
