### ISSUE TITLE
Invalid post request crashes chaincode..

### ISSUE THREAD

**Issue by everledger** [hyperledger/hyperledger#27]
I sent a post request with an invalid query parameter and shim handler crashed

//chaincode 
2016/05/03 10:18:12 [880a64f1]Query completed. Sending QUERY_COMPLETED
2016/05/03 10:41:15 [09d80ccb]Received message QUERY from shim
2016/05/03 10:41:15 [09d80ccb]Handling ChaincodeMessage of type: QUERY(state:ready)
2016/05/03 10:41:15 [09d80ccb]Sending GET_STATE
2016/05/03 10:41:15 [09d80ccb]Received message RESPONSE from shim
2016/05/03 10:41:15 [09d80ccb]Handling ChaincodeMessage of type: RESPONSE(state:ready)
2016/05/03 10:41:15 [09d80ccb]before send
2016/05/03 10:41:15 [09d80ccb]after send
2016/05/03 10:41:15 [09d80ccb]Received RESPONSE, communicated (state:ready)
2016/05/03 10:41:15 [09d80ccb]GetState received payload RESPONSE
2016/05/03 10:41:15 passed row [{[]}]
Query Response:{"Owner":"{[]}"}
panic: runtime error: index out of range
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x489f32]

goroutine 83 [running]:
panic(0x974440, 0xc82000a110)
        /opt/go/src/runtime/panic.go:464 +0x3e6
github.com/hyperledger/fabric/core/chaincode/shim.(*Handler).serialSend(0xc820056380, 0x0, 0x0, 0x0)
        /opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/shim/handler.go:73 +0x582
github.com/hyperledger/fabric/core/chaincode/shim.(*Handler).handleQuery.func1.1(0xc820056380, 0xc820201e20)
        /opt/gopath/src/github.com/hyperledger/fabric/core/chaincode/shim/handler.go:320 +0x2e
panic(0x974440, 0xc82000a0c0)
        /opt/go/src/runtime/panic.go:426 +0x4e9
main.(*AssetManagementChaincode).Query(0xd3a060, 0xc820218900, 0xc82021e1f5, 0x5, 0xc82021e200, 0x1, 0x1, 0x0, 0x0, 0x0, ...)

 curl -i -X POST -H "Content-Type: application/json" http://localhost:5000/chaincode  -d '{  "jso
nrpc": "2.0",  "method": "query",  "params": {      "type": 1,      "chaincodeID":{          "name":"mycc"      },
 "ctorMsg": {         "function":"query",         "args":["a"]      }  },  "id": 5}'
HTTP/1.1 200 OK
Access-Control-Allow-Headers: accept, content-type
Access-Control-Allow-Origin: *
Content-Type: application/json
Date: Tue, 03 May 2016 10:41:45 GMT
Content-Length: 204

**Comment by christo4ferris** [comment]
@everledger thanks for raising this issue. However, it was raised against the incorrect repo. Would you please close this one and open the issue against https://github.com/hyperledger/fabric/issues. thanks!

**Comment by christo4ferris** [comment]
opened new issue https://github.com/hyperledger/fabric/issues/1811 and closing this as it is misplaced. Thanks for submitting @everledger
