### ISSUE TITLE
Slack Channel?

### ISSUE THREAD

**Issue by freakynit** [hyperledger/hyperledger#4]
Hi,

Congrats for the great initiative. Just wanna know/suggest slack channel for realtime collaboration.

Thanks...

**Comment by morenoh149** [comment]
or gitter

**Comment by jeffscottward** [comment]
+1.
Mailing lists are old school, can't be bothered. Those are for pull
requests, not glacial speed conversation.

**Comment by EtherTyper** [comment]
I think using a proprietary platform for development would be against their standards nowadays. Slack has every right to cease to license the Linux Foundation's usage of it. A large example of this has happened before is BitKeeper, and we all know how that ended up. Perhaps a more open platform at its core, like a self-hosted Gitter engine? But, overall, :+1: for new communication platforms.

**Comment by tbenzies** [comment]
@freakynit to join the Hyperledger Project Slack, please go to https://hyperledgerproject.slack.com/signup.  If your domain is not on there, please just shoot me a message so that I can whitelist it.

**Comment by EtherTyper** [comment]
@toddbenzies How about gmail.com, outlook.com, and hotmail.com for us who
can't setup a web server by ourselves? Also, I would appreciate my own
domain, ethertyper.com, if I can set that up.

Can I connect through any of these means?

Thanks,
The EtherTyper

**Comment by jeffscottward** [comment]
Please add consensys.net please

**Comment by TheMikeMaxey** [comment]
and pivotal.io


On Wed, Feb 17, 2016 at 2:24 PM Jeff Ward <notifications@github.com> wrote:

> Please add consensys.net please
> On Wed, Feb 17, 2016 at 5:22 PM ELI JOSEPH BRADLEY <
> notifications@github.com>
> wrote:
>
> > @toddbenzies How about gmail.com, outlook.com, and hotmail.com for us
> who
> > can't setup a web server by ourselves? Also, I would appreciate my own
> > domain, ethertyper.com, if I can set that up.
> >
> > Can I connect through any of these means?
> >
> > Thanks,
> > The EtherTyper
> >
> > On Wed, Feb 17, 2016, 4:17 PM Todd Benzies <notifications@github.com>
> > wrote:
> >
> > > @freakynit <https://github.com/freakynit> to join the Hyperledger
> > Project
> > > Slack, please go to https://hyperledgerproject.slack.com/signup. If
> your
> > > domain is not on there, please just shoot me a message so that I can
> > > whitelist it.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/hyperledger/hyperledger/issues/4#issuecomment-185432132
> > >
> > > .
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/hyperledger/hyperledger/issues/4#issuecomment-185433948
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hyperledger/hyperledger/issues/4#issuecomment-185434648>
> .
>
-- 
------------------------------
Mike Maxey | Senior Director
Strategy & Corporate Development | Pivotal
Mobile: 415 627 8242 | mmaxey@pivotal.io

This email message and any files transmitted with it may contain
confidential information intended only for the person(s) to whom this email
is addressed. If you received this email in error, please notify Mike Maxey
immediately and destroy the original message without forwarding or making a
copy. Thank you.

**Comment by ccerrato147** [comment]
@tbenzies Are you going to allow for gmail accounts?

**Comment by lsseckman** [comment]
@tbenzies can we get @pwc.com ?

**Comment by tbenzies** [comment]
@jeffscottward - done
@EtherTyper - unfortunately Slack does not allow whitelisting gmail, hotmail, etc.  Please send me your email address and I can issue a personal invite.
@TheMikeMaxey - done
@ccerrato147 - unfortunately Slack does not allow whitelisting gmail, hotmail, etc.  Please send me your email address and I can issue a personal invite.

**Comment by tbenzies** [comment]
@lsseckman - done

**Comment by EtherTyper** [comment]
@tbenzies Okay. Can you whitelist ethertyper.com?

**Comment by tbenzies** [comment]
@EtherTyper - done

**Comment by ccerrato147** [comment]
@tbenzies my personal email is ccerrato147@gmail.com

**Comment by Alexkane** [comment]
Please whitelist Songtrust.com and dmpgroup.com

**Comment by tbenzies** [comment]
@Alexkane - done

**Comment by techthumb** [comment]
techthumb.in please

**Comment by tbenzies** [comment]
@techthumb - done

**Comment by zmanian** [comment]
skuchain.com. Thanks

**Comment by sugruedes** [comment]
@tbenzies 
Add akreditas.com  - please!

thanks

**Comment by sugruedes** [comment]
@tbenzies 
Much obliged!  :-)

**Comment by ianjcarman** [comment]
Please add taskinnovations.com

**Comment by ayalan** [comment]
@tbenzies If possible please add ayalan@gmail.com  Thank you!

**Comment by Horizon88** [comment]
@tbenzies please enable kyc-chain.com Thank you.

**Comment by everbasler** [comment]
@tbenzies Please add everchain.io

**Comment by zamrokk** [comment]
@tbenzies Please add @fr.ibm.com

**Comment by jbowkett** [comment]
@tbenzies Please add @luxoft.com
Thanks,
James

**Comment by peterfh** [comment]
Hi, @tbenzies, I've been looking forwards to this project going open-source.

Could you add @evry.com to the whitelist as well?

**Comment by pniang** [comment]
Hello @tbenzies, can you please add poniang@gmail.com. Thank you.

**Comment by jesper** [comment]
@tbenzies  please add @jespersaur.com. Thanks.

**Comment by mdangear** [comment]
can you add me? marc@dangeard.com - I work on CommonAccord -
www.commonaccord.org but no email for this domain

On Thu, Feb 18, 2016 at 1:15 PM, Jesper Thomschütz <notifications@github.com

**Comment by yinyee** [comment]
Please add kanyinyee@gmail.com <mailto:kanyinyee@gmail.com> too, thanks!

**Comment by vdorut** [comment]
Please add v.dorut@gmail.com . THX

**Comment by adamdecaf** [comment]
Please add adamkshannon@gmail.com

**Comment by michaelrowe01** [comment]
can you add mrmikerowe@us.ibm.com to the slack
Michael Rowe
 
 
----- Original message -----From: Adam Shannon <notifications@github.com>To: hyperledger/hyperledger <hyperledger@noreply.github.com>Cc:Subject: Re: [hyperledger] Slack Channel? (#4)Date: Thu, Feb 18, 2016 9:47 AM 
Please add adamkshannon@gmail.com

**Comment by takagimasanobu** [comment]
Please add masanobu@jp.ibm.com. Thanks.

**Comment by pdhoward** [comment]
Please add
patrick.howard@xiollc.com


Date: Thu, 18 Feb 2016 04:22:46 -0800

**Comment by tbenzies** [comment]
All requests above have been processed.

**Comment by dazraf** [comment]
Please add farzad.pezeshkpour@gmail.com

**Comment by naddison36** [comment]
Please add @addisonbrown.com.au
Thanks

**Comment by quiquee** [comment]
Can you please add enrique.melero@gmail.com ?

**Comment by dazraf** [comment]
would be very grateful if you would also add
@rbs.com and @rbs.co.uk

Thank you
Farzad

**Comment by kendagor** [comment]
Please add kendagor@gmail.com

Thanks

Kendagor

**Comment by phpkev** [comment]
Please add kevtech@gmail.com. Thanks!

**Comment by Daido** [comment]
Please add ratabayev@gmail.com. Thanks!

**Comment by bentoncbainbridge** [comment]
Please add @bentoncbainbridge.com thanks!!

**Comment by genggjh** [comment]
Please add david@esse.io 
thanks a lot.

David

**Comment by pniang** [comment]
Please add poniang@gmail.com. Thank you.

**Comment by kurttheviking** [comment]
Please add @blacktuliplabs.com -- thanks!

**Comment by NickJT** [comment]
Hi Todd. Could you add @euronext.com to the whitelist please. 

 

Many thanks

**Comment by amit0623** [comment]
Please add amitarora0623@gmail.com

**Comment by ls84** [comment]
Please add liu@shuo.email, thanks a lot

**Comment by Pabloces** [comment]
Please Add @flexibility.com.ar. Thanks.

**Comment by HazardJ** [comment]
Please add james.g.hazard@gmail.com

**Comment by tim0k** [comment]
Please add timo.kupsa@gmail.com Thanks!

**Comment by tbenzies** [comment]
Everything above has been processed.  All future requests send to tbenzies@linuxfoundation.org

**Comment by kobigurk** [comment]
Please add @magicinbits.com

**Comment by asanz** [comment]
please add alex@nscoder.co.uk

Thanks

2016-02-18 12:22 GMT+00:00 Marc Dangeard <notifications@github.com>:

**Comment by juanfranblanco** [comment]
Please add juanfranblanco@hotmail.com

Date: Tue, 23 Feb 2016 02:45:39 -0800

**Comment by abhineshwar** [comment]
Please add abhineshwartomar@gmail.com

**Comment by shanjit** [comment]
Please add shanjitsingh@gmail.com

**Comment by vaughnshinall-temboo** [comment]
Could you add vaughn.shinall@temboo.com ?

Thanks!

**Comment by ttmc** [comment]
It would be nice if you could move these Slack invitation requests out of comments on a GitHub Repository Issue, so people "watching" the repo aren't constantly spammed. Here are two examples of how other organizations have done that well:

https://ghost.org/slack/

http://slack.rethinkdb.com/

**Comment by davidwowa** [comment]
dmcvic@web.de

Thx.

**Comment by richvincent** [comment]
Please add rich@richardvincent.com

**Comment by nybek** [comment]
Please add @nybek.com. Thanks.

As per the instructions earlier in this thread, I sent an email to 
tbenzies@linuxfoundation.org on Monday requesting the same. However,
I never heard anything back, so I'm assuming the email was filtered.

**Comment by randomdigit** [comment]
Please add randysblair@gmail.com.

**Comment by edrasin** [comment]
please add eric.drasin@gmail.com

On Thu, Feb 25, 2016 at 7:06 AM, randomdigit <notifications@github.com>
wrote:

> Please add randysblair@gmail.com.
>
> Sent from the ether
>
>
> > On Feb 25, 2016, at 5:41 AM, nybek <notifications@github.com> wrote:
> >
> > Please add @nybek.com. Thanks.
> >
> > As per the instructions earlier in this thread, I sent an email to
> > tbenzies@linuxfoundation.org on Monday requesting the same. However,
> > I never heard anything back, so I'm assuming the email was filtered.
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hyperledger/hyperledger/issues/4#issuecomment-188755399>
> .
>



-- 
Eric Barry Drasin <http://ericbarrydrasin.com>
@edrasin <http://twitter.com/edrasin>
*blog <http://ericbarrydrasin.tumblr.com> *
Fast Food Collective <http://fastfoodcollective.tumblr.com>

**Comment by agkannachankudy** [comment]
Please add agafoor@gmail.com and agkannachankudy@statestreet.com

**Comment by tbenzies** [comment]
@nybek - this is complete.

**Comment by jellevdp** [comment]
@tbenzies ; Hi Todd, could you also please whitelist @nl.ibm.com, @be.ibm.com, @ing.com and @bnpparibasfortis.com ?

Many thanks!

**Comment by nuxeh** [comment]
Freenode?

**Comment by awalias** [comment]
can you add antwilson@hotmail.co.uk

Date: Fri, 26 Feb 2016 02:51:14 -0800

**Comment by joshuajeeson** [comment]
@tbenzies, Please whitelist @bt.com

Thanks, Josh.

**Comment by realcodywburns** [comment]
Please whitelist @uh.edu

**Comment by janx** [comment]
@tbenzies please whitelist @cryptape.com, thanks!

**Comment by thedoctor** [comment]
@tbenzies please whitelist @gem.co thanks :)

**Comment by sandisk** [comment]
@tbenzies Please whitelist @factury.co. Thank you!

**Comment by renatco** [comment]
@tbenzies Please whitelist @altoros.com.

Thanks,
Renat

**Comment by filipegarcia** [comment]
@tbenzies Please whitelist @crosslend.com 

Thank you

**Comment by thanii** [comment]
@tbenzies Please whitelist @ktwoo.com    and @xerrow.com

**Comment by naohiko** [comment]
@tbenzies Please add uramoto@gmail.com.

**Comment by jpsbali** [comment]
@tbenzies Please add jpsbali@gmail.com

**Comment by jpsbali** [comment]
Also please whitelist citigroup.com and citi.com .. Thanks.

**Comment by ibmamnt** [comment]
I'm already participating to the Slack. This is for recording purpose that I'm willing to participate to the activity. amnt@jp.ibm.com

**Comment by nivertech** [comment]
@tbenzies Please add zvi@nivertech.com

**Comment by tbenzies** [comment]
Hi all -- you can now self-generate an invite at https://slack.hyperledger.org/.

**Comment by morenoh149** [comment]
@tbenzies you should lock the thread
