### ISSUE TITLE
This application cannot run without the blockchain network :(

### ISSUE THREAD

**Issue by shambhavi1993** [hyperledger/hyperledger#45]
I'm running cp-web application, but this error is coming:
This application cannot run without the blockchain network :(

Please let me know is this the issue with the network  itself and how can it be resolved?

**Comment by shambhavi1993** [comment]
I've successfully got the interface up and running on my machine, however I'm not able to trade, create

Error when querying chaincode: Error: state may be inconsistent, cannot query' },
  id: 1471518308353 }
company undefined
[ibc-js] Unresolved action, must poll

What's going wrong?

**Comment by morenoh149** [comment]
it should not surprise you that this code does not work. I've been following it out of interest but the project was stopped, the core team went on to work on a private company to flesh out the ideas here. Would love to see your issue resolved? :)

**Comment by christo4ferris** [comment]
@shambhavi1993 cp-web is not a hyperledger project, though it does make use of the Hyperledger fabric that is deployed in IBM Bluemix. You will likely receive a response by posting an issue [there](https://github.com/IBM-Blockchain/cp-web/issues).
