### ISSUE TITLE
Licensing evaluation of candidate submissions

### ISSUE THREAD

**Issue by gerrith3** [hyperledger/hyperledger#5]
Is the TSC providing an evaluation of the License and Copyright of the contributions as a first level assessment of the code?  It seems that two are released under Apache license (good) and two are much more ambiguous about License and Copyright, e.g. can the License even be changed for the other two contributions given the ambiguity in the copyright holders?  Can someone summarize the findings in that regard, and will there be a process for ensuring that all submitted code is "owner owned" and free to be released to the project?

**Comment by mkdolan** [comment]
Hi, any code that is brought into Hyperledger must be done so under the Apache 2 license or receive explicit approval from the Governing Board as an exception. I would expect anything that is not an upstream library required as a dependency should be relicensed Apache 2 by the time it goes into Hyperledger. The Hyperledger Charter makes it clear what's required for contributing in the IP Policy section. 

[https://www.hyperledger.org/about/charter](https://www.hyperledger.org/about/charter)

**Comment by christo4ferris** [comment]
think this can be closed given @mkdolan response
