### ISSUE TITLE
Now I have 4HOST, the one for  memservc  & VP0, and  the other 3HOST for VP connection with VP0

### ISSUE THREAD

**Issue by zhangzhen30** [hyperledger/hyperledger#52]
one host docker-compose.yml.
membersrvc:
  image: hyperledger/fabric-membersrvc:latest
  restart: unless-stopped
  expose:
    - "7054"
  volumes: 
    - /var/run/docker.sock:/var/run/docker.sock
  command: membersrvc  

vp0:
  extends:
    file: peer-pbft.yml
    service: vp
  hostname: vp0
  environment:
    - CORE_PEER_ID=vp0
    - CORE_SECURITY_ENABLED=true
    - CORE_SECURITY_ENROLLID=test_vp0
    - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
    - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
  ports:
    - "7050:7050"
  links:
    - membersrvc
  command: sh -c "sleep 5; peer node start"

AND peer-pbft.yml
p:
  image: hyperledger/fabric-peer:latest
  restart: unless-stopped
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_PEER_NETWORKID=dev
    - CORE_LOGGING_LEVEL=info  #critical, error, warning, notice, info, debug
    # The following section enables pbft consensus
    - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft  # noops, pbft
    - CORE_PBFT_GENERAL_MODE=batch  # batch. classic and sieve will be not supported again.
    - CORE_PBFT_GENERAL_N=4
    - CORE_PBFT_GENERAL_BATCHSIZE=2  # only useful when in batch mode
    - CORE_PBFT_GENERAL_TIMEOUT_REQUEST=2s
  expose:
    - "7051"
    - "7052"
    - "7053"
  volumes: # docker.sock is mapped as the default CORE_VM_ENDPOINT
    - /var/run/docker.sock:/var/run/docker.sock
  command: peer node start  # this repeats the default cmd to make sure

The other 3 HOST
vp1:
  extends:
    file: peer-pbft.yml
    service: vp
  hostname: vp1
  environment:
    - CORE_PEER_ID=vp1
    - CORE_SECURITY_ENABLED=true
    - CORE_SECURITY_ENROLLID=test_vp1
    - CORE_SECURITY_ENROLLSECRET=5wgHK9qqYaPy
    - CORE_PEER_PKI_ECA_PADDR=vp0.git.com:7054
    - CORE_PEER_PKI_TCA_PADDR=vp0.git.com:7054
    - CORE_PEER_PKI_TLSCA_PADDR=vp0.git.com:7054
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
  ports:
    - "7050:7050"
  command: sh -c "sleep 5; peer node start  --peer-chaincodedev"

=========================================
 they can  work  with out memservc  .
now I introduced memservc on the 1HOST is runing ,but other 3 HOST don't work.

The log :

vp1_1  | 07:52:02.674 [nodeCmd] serve -> INFO 001 Running in chaincode development mode
vp1_1  | 07:52:02.674 [nodeCmd] serve -> INFO 002 Set consensus to NOOPS and user starts chaincode
vp1_1  | 07:52:02.674 [nodeCmd] serve -> INFO 003 Disable loading validity system chaincode
vp1_1  | 07:52:02.675 [peer] func1 -> INFO 004 Auto detected peer address: 172.17.0.2:7051
vp1_1  | 07:52:02.675 [peer] func1 -> INFO 005 Auto detected peer address: 172.17.0.2:7051
vp1_1  | 07:52:02.677 [nodeCmd] serve -> INFO 006 Security enabled status: true
vp1_1  | 07:52:02.677 [nodeCmd] serve -> INFO 007 Privacy enabled status: false
vp1_1  | 07:52:02.680 [eventhub_producer] start -> INFO 008 event processor started
vp1_1  | 07:52:02.742 [crypto] RegisterValidator -> INFO 009 Registering validator [test_vp1] with name [test_vp1]...
vp1_1  | 2016/09/10 07:52:05 Failed to dial vp0.git.com:7054: grpc: timed out trying to connect; please retry.
vp1_1  | 07:52:05.745 [crypto] Errorf -> ERRO 00a [validator.test_vp1] Failed requesting read certificate [rpc error: code = 2 desc = "grpc: the client connection is closing"].
vp1_1  | 07:52:05.745 [crypto] Errorf -> ERRO 00b [validator.test_vp1] Failed requesting ECA certificate [rpc error: code = 2 desc = "grpc: the client connection is closing"].
vp1_1  | 07:52:05.745 [crypto] Errorf -> ERRO 00c [validator.test_vp1] Failed getting ECA certificate [rpc error: code = 2 desc = "grpc: the client connection is closing"].
vp1_1  | 07:52:05.745 [crypto] Errorf -> ERRO 00d [validator.test_vp1] Failed retrieving ECA certs chain [rpc error: code = 2 desc = "grpc: the client connection is closing"].
vp1_1  | 07:52:05.745 [crypto] Errorf -> ERRO 00e [validator.test_vp1] Failed registering node crypto engine [rpc error: code = 2 desc = "grpc: the client connection is closing"].
vp1_1  | 07:52:05.745 [crypto] Errorf -> ERRO 00f [validator.test_vp1] Failed registering peer [test_vp1]: [rpc error: code = 2 desc = "grpc: the client connection is closing"]
vp1_1  | 07:52:05.745 [crypto] Errorf -> ERRO 010 [validator.test_vp1] Failed registering [test_vp1]: [rpc error: code = 2 desc = "grpc: the client connection is closing"]
vp1_1  | 07:52:05.745 [crypto] RegisterValidator -> ERRO 011 Failed registering validator [test_vp1] with name [test_vp1] [rpc error: code = 2 desc = "grpc: the client connection is closing"].

===============================================
what's the reason? who can help me ? THX

**Comment by bercinho** [comment]
Hi, 

I have this problem as well. Can you please tell me how you resolved?

Thanks

**Comment by ume0202** [comment]
Hi, any solution for the above scenario/issue.?
