### ISSUE TITLE
fabric example02 query  error : "code":-32003,"message":"Query failure"

### ISSUE THREAD

**Issue by zhangzhen30** [hyperledger/hyperledger#53]
[root@vp4 ~]# POST 127.0.0.1:7050/chaincode
Please enter content (application/x-www-form-urlencoded) to be POSTed:
{
  "jsonrpc": "2.0",
  "method": "query",
  "params": {
      "type": 1,
      "chaincodeID":{
          "name":"09812cbf9ac249d9fb4ebd38b21a7c35656c12f89ef117e7c47f5ddc9437b6fa17ea754edeeb868eedadfcaae6488fce8beb0f675a927b07df8d18c0c2718dae"          
      },
      "ctorMsg": {
         "function":"query",
         "args":["b"]
      },
      "secureContext": "jim"
  },
  "id": 5
}{"jsonrpc":"2.0","error":{"code":-32003,"message":"Query failure","data":"Error when querying chaincode: Error:Failed to launch chaincode spec(Could not get deployment transaction for 09812cbf9ac249d9fb4ebd38b21a7c35656c12f89ef117e7c47f5ddc9437b6fa17ea754edeeb868eedadfcaae6488fce8beb0f675a927b07df8d18c0c2718dae - LedgerError - ResourceNotFound: ledger: resource not found)"},"id":5}

**Comment by christo4ferris** [comment]
@zhangzhen30 we are using JIRA to track issues for the Hyperledger fabric project. You'll need a Linux ID (free) at [identity.linuxfoundation.org](https://identity.linuxfoundation.org/) and can post/track issues at [jira.hyperledger.org](http://jira.hyperledger.org).

**Comment by zhangzhen30** [comment]
THX @christo4ferris
