### ISSUE TITLE
eca.cert.chain: no such file or directory

### ISSUE THREAD

**Issue by yelvxiuge** [hyperledger/hyperledger#59]
Edit a file named docker-compose.yml via vim,here're content below:

membersrvc:
  image: hyperledger/fabric-membersrvc
  ports:
    - "7054:7054"
  command: membersrvc
vp0:
  image: hyperledger/fabric-peer
  ports:
    - "7050:7050"
    - "7051:7051"
    - "7053:7053"
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_ID=vp0
    - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
    - CORE_SECURITY_ENABLED=true
    - CORE_SECURITY_ENROLLID=test_vp0
    - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
  links:
    - membersrvc
  command: sh -c "sleep 20; peer node start --peer-chaincodedev"

run commands:

1,docker-composer up
return a warn:
    [sysccapi] RegisterSysCC -> WARN 05e Currently system chaincode does support security(noop,github.com/hyperledger/fabric/bddtests/syschaincode/noop)

2, ./peer network login jim

3, ./peer  chaincode deploy -n mycc -c '{ "Args" : ["init", "a","100", "b", "200"]}'

Error: Error building chaincode: rpc error: code = 5 desc = open /var/hyperledger/production/crypto/client/ks/raw/eca.cert.chain: no such file or directory

**Comment by christo4ferris** [comment]
Hi yelvxiuge,

Thanks for submitting this issue!

We use JIRA to track issues. we are using JIRA to track issues for the Hyperledger fabric project. You'll need a Linux ID (free) at [identity.linuxfoundation.org](https://identity.linuxfoundation.org/) and can post/track issues at [jira.hyperledger.org](http://jira.hyperledger.org). 

hyperbot

**Comment by yelvxiuge** [comment]
Yes,I have it

**Comment by christo4ferris** [comment]
@yelvxiuge ok, please close this when you have opened the issue in JIRA. Thanks
