### ISSUE TITLE
PreviousHash of one block  does not match  the StateHash of it's previous block 

### ISSUE THREAD

**Issue by zhangfz** [hyperledger/hyperledger#60]
the enviroment is   fabric( v0.6) with single peer node , get block infomation from rest service (7050)
PreviousHash of one block  does not match  the StateHash of it's previous block literally
for example:
block 3 has a previousBlockHash "LONqFDCzSBbAJWXejefpJnR70rmGaQtnms3yvIBTfyMzZyWDBZ4p6cBR+UVMUDp8EhmmTYMKYYjMupXjI9+Yzw=="

while block 2 has a stateHash "u9Oc98t4jNniDSF5j+6K+V1UW/wD8dr709kwSU8DxlGrfZljwWa0g0HAa5cvyRiqjCkaxnu5FfcxzYShvEXKpg==" 

Does it make sense ?

Another problem is that the block 1 does not have stateHash field.
It does not make any sense either.

**Comment by christo4ferris** [comment]
Hi zhangfz,

Thanks for submitting this issue!

We use JIRA to track issues. we are using JIRA to track issues for the Hyperledger fabric project. You'll need a Linux ID (free) at [identity.linuxfoundation.org](https://identity.linuxfoundation.org/) and can post/track issues at [jira.hyperledger.org](http://jira.hyperledger.org). 

hyperbot
