### ISSUE TITLE
Docker problem

### ISSUE THREAD

**Issue by aymanx1** [hyperledger/hyperledger#61]
I've pulled the images and when i try to run `docker-compose up` evrything runs ok except it stucks at this message :

```
[33mvp0_1         |[0m [36m15:56:36.445 [peer] ensureConnected -> DEBU 14a4[0m Touch service indicates no dropped connections
[33mvp0_1         |[0m [36m15:56:36.445 [peer] ensureConnected -> DEBU 14a5[0m Connected to: []
[33mvp0_1         |[0m [36m15:56:36.445 [peer] ensureConnected -> DEBU 14a6[0m Discovery knows about: []
```

for more than 1 hour what'going on?

**Comment by christo4ferris** [comment]
Hi aymanx1,

Thanks for submitting this issue!

We use JIRA to track issues. we are using JIRA to track issues for the Hyperledger fabric project. You'll need a Linux ID (free) at [identity.linuxfoundation.org](https://identity.linuxfoundation.org/) and can post/track issues at [jira.hyperledger.org](http://jira.hyperledger.org). 

hyperbot
