### ISSUE TITLE
Hyperledger Fabric “Error when deploying chaincode: Failed loading TCerts from TCA”

### ISSUE THREAD

**Issue by khut-pidor** [hyperledger/hyperledger#62]
I have 1 membersrvc and 2 validating peers with security enable. I run 1 validating peer and membersrvc together in 1 vm (1st peer) and another 1 validating peer (2nd peer) in other vm. I successful from a network and connect the peers together. While I try to use the 2nd validating to login with user in membersrvc.yaml of 1st peer. It's fine. The status is "OK ...." After register sample chaincode (chaincode_example02) of fabric defualt v0.6, I tried to init the chaincode with the help of Postman and it load error

**{ "jsonrpc": "2.0", 
"error":
 { "code": -32001, 
"message": "Deployment failure", 
_"data": "Error when deploying chaincode: Failed loading TCerts from TCA"_ }, 
"id": 1 
}**

Again, while I disable the security in core.yaml of each peer, start the peers again without membersrvc start. I tried to init the 2nd peers. I am able to make it. SO I think the problem is causing from security enable, but in my scenario to used membersrvc is needed.

I try to surf around about TCerts & TCA, but I couldn't find any clear explanation and how to did it.
I found [one](http://hyperledger-fabric.readthedocs.io/en/latest/Setup/TLSSetup.html), I follow ,but I cannot find certificate.crt, what about to overwrite CN. I think it's not work I try to follow other, 
it ask me to set the root certificate and it's path "tlsca.cert". I know it locate at  --/var/hyperledger/production/.membersrvc, when I try to put it in membersrvc.yaml with the path and tlsca.cert ("/var/hyperledger/production/.membersrvc/tlsca.cert"), and start membersrvc, it loads, cannot file any directory or file

Any suggestions toward this problems ?

*Note I am not using vagrant or docker. I install Fabric directly to separate VM

**Comment by christo4ferris** [comment]
Hi khut-pidor,

Thanks for submitting this issue!

We use JIRA to track issues. we are using JIRA to track issues for the Hyperledger fabric project. You'll need a Linux ID (free) at [identity.linuxfoundation.org](https://identity.linuxfoundation.org/) and can post/track issues at [jira.hyperledger.org](http://jira.hyperledger.org). 

hyperbot
