### ISSUE TITLE
npm install hfc "[Throwing Errors]"

### ISSUE THREAD

**Issue by coderundebug12** [hyperledger/hyperledger#63]
Hi All , I am unable to install hfc sdk through npm  , I also tried dong it manually, but its not workings.

**Comment by christo4ferris** [comment]
Hi coderundebug12,

Thanks for submitting this issue!

We use JIRA to track issues. we are using JIRA to track issues for the Hyperledger fabric project. You'll need a Linux ID (free) at [identity.linuxfoundation.org](https://identity.linuxfoundation.org/) and can post/track issues at [jira.hyperledger.org](http://jira.hyperledger.org). 

hyperbot
