### ISSUE TITLE
what is a "Premier Member"?

### ISSUE THREAD

**Issue by jonschlinkert** [hyperledger/hyperledger#65]
The [charter on hyperledger.org](https://www.hyperledger.org/about/charter) makes repeated mention of "Premium Members" and their privileged status, but never explain what a premium member is. This seems like material information, and it seems reasonable for the open source community to expect the charter to explain "membership types" and how they work in full detail. Moreover, what is the "membership type" of a contributor who gives their free time in good faith to this initiative? 

Fwiw, I looked for a GitHub repository where the code for hyperledger.org might be hosted so that I could raise the issue there, but didn't find one. It appears that Jira is used for issue tracking as well as source control. I'm guessing that GitHub is mostly a marketing channel for "getting in front of devs"?

**Comment by christo4ferris** [comment]
Hi jonschlinkert,

Thanks for submitting this issue!

We use JIRA to track issues. we are using JIRA to track issues for the Hyperledger fabric project. You'll need a Linux ID (free) at [identity.linuxfoundation.org](https://identity.linuxfoundation.org/) and can post/track issues at [jira.hyperledger.org](http://jira.hyperledger.org). 

hyperbot

**Comment by jonschlinkert** [comment]
Hi christo4ferris/hyperbot: an answer here is fine. Thanks.

**Comment by christo4ferris** [comment]
A "Premier" member is defined in the Charter. Essentially, they pay a premium membership fee. There are three classes of membership, Premier, General and Associate - pretty standard for open source orgs. It is all defined in the Charter. 

Membership is not required to participate in the technical development of any of the projects in the Hyperledger umbrella.

**Comment by jonschlinkert** [comment]
Thanks for the information. I can't find what you're referring to anywhere though, I only see information about the "rights" afforded to premium members, but not how to become one. I was hoping there was a chance of us becoming a premium member if it's not out of the realm of possibilities. But I can't find any info on it.

**Comment by christo4ferris** [comment]
https://www.hyperledger.org/about/join

**Comment by jonschlinkert** [comment]
Thanks that's all I needed to know. Might be good to link to that in the charter.
