### ISSUE TITLE
Hyperledger Clustering

### ISSUE THREAD

**Issue by selvarajdh** [hyperledger/hyperledger#66]

**Comment by christo4ferris** [comment]
Hi selvarajdh,

Thanks for submitting this issue!

We use JIRA to track issues. we are using JIRA to track issues for the Hyperledger fabric project. You'll need a Linux ID (free) at [identity.linuxfoundation.org](https://identity.linuxfoundation.org/) and can post/track issues at [jira.hyperledger.org](http://jira.hyperledger.org). 

hyperbot
