### ISSUE TITLE
Iroha Resources - 404 Error - White Paper Link

### ISSUE THREAD

**Issue by thaddeus-cambron** [hyperledger/hyperledger#70]
**Iroha Resources Page**
https://www.hyperledger.org/projects/iroha/resources

- Click on "**Read the White Paper**" link 
- Returns a 404 Error Page from GitHub

https://github.com/hyperledger/iroha/blob/master/docs/iroha_whitepaper.md

**Comment by ryjones** [comment]
thanks for this report. The website has been re-done. I looked and the new page doesn’t have a direct link to the whitepaper so I think time has passed this by
