### ISSUE TITLE
Functions that chaincode executes

### ISSUE THREAD

**Issue by ClementeSerrano** [hyperledger/hyperledger#71]
Hi guys! I'm currently working in a big project that uses Hyperledger Fabric and I have a big question about the ledger-update process. Bellow I attached the business process that I design (based Hyperledger docs). I need to know if its good.

One of my main question is to know specifically which are the functions that chaincode executes and which ones that the node executes

![ledger-update-business-process-hyperledger](https://user-images.githubusercontent.com/9727036/46561881-f80a2500-c8cf-11e8-9c46-a291597e567d.jpg)

**Comment by ryjones** [comment]
join us on [chat!](https://chat.hyperledger.org/channel/fabric)
