### ISSUE TITLE
Testing with my own certificates

### ISSUE THREAD

**Issue by saragon** [hyperledger/hyperledger#72]
Hi,

I would like to aggregate my own certificates in hyperledger network using fabric server. For it, I have downloaded the fabric-samples repo from github and used fabric-ca for testing, but the root ca container doesn't even rised up.

For this, in start-root-ca.sh I have added the following sentence:
`fabric-ca-server init --ca.certfile MY_PEM_CERTIFICATE --ca.keyfile MY_KEY`
and the error is:

> Error: Validation of certificate and key failed: Invalid certificate in file 'XXXX': The 'cert sign' key usage is required

That means that I need my own csr too, so I was researching and I found in the hyperledger official documentation two apparent solutions:

1. Inserting a flag as following: `fabric-ca-server init -n  --csr.cn string --csr.hosts stringSlice --csr.keyrequest.algo string --csr.keyrequest.size int --csr.serialnumber string`
[Fabric-CA Server’s CLI](https://hyperledger-fabric-ca.readthedocs.io/en/release-1.4/servercli.html)
2. Making a csr.json which I can customize as desired
[Fabric CA Server](https://fabrictestdocs.readthedocs.io/en/latest/Setup/ca-setup.html)

Both of the solutions don't work, and the error is that "The field XXX is not recognized" (XXX = csr.json argument or the parameters after flags).

Does some solution exist for this?

**Comment by ryjones** [comment]
Thanks for the contribution! However, this is a read-only mirror. please read the [contribution guide](https://hyperledger-fabric.readthedocs.io/en/latest/CONTRIBUTING.html#reporting-bugs). Also, feel free to join us on [chat!](https://chat.hyperledger.org/channel/fabric)
